name: catkin_make_isolated

on: [push]

jobs:
  build-18-melodic:
    runs-on: [ubuntu-18.04]
    strategy:
      fail-fast: false
      matrix:
        compiler: ["-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++", "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"]
    steps:
    - uses: actions/checkout@v1
      with:
        path: ws/src/gerona
    - name: clone_dependencies
      run: |
        cd ..
        git clone https://github.com/cogsys-tuebingen/cslibs_path_planning
        git clone https://github.com/cogsys-tuebingen/cslibs_navigation_utilities
        git clone https://github.com/sbpl/sbpl
    - uses: betwo/github-setup-catkin@v1.1.1
      with:
        ros-version: 'melodic'
        workspace: $HOME/work/gerona/ws
    - name: build
      run: |
        cd $HOME/work/gerona/ws
        sudo apt-get install -qq -y gcc clang
        catkin_make_isolated ${{ matrix.compiler }}

  build-20-noetic:
    runs-on: [ubuntu-20.04]
    strategy:
      fail-fast: false
      matrix:
        compiler: ["-DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++", "-DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"]
    steps:
    - uses: actions/checkout@v1
      with:
        path: ws/src/gerona
    - name: clone_dependencies
      run: |
        cd ..
        git clone https://github.com/cogsys-tuebingen/cslibs_path_planning
        git clone https://github.com/cogsys-tuebingen/cslibs_navigation_utilities
        git clone https://github.com/sbpl/sbpl
    - uses: betwo/github-setup-catkin@v1.1.1
      with:
        ros-version: 'noetic'
        workspace: $HOME/work/gerona/ws
    - name: build
      run: |
        cd $HOME/work/gerona/ws
        sudo apt-get install -qq -y gcc clang
        catkin_make_isolated ${{ matrix.compiler }}
